//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATİSLAR
    {
        public int SATİSİD { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> MUSTERİ { get; set; }
        public Nullable<short> ADET { get; set; }
    
        public virtual TBLMUSTERİLER TBLMUSTERİLER { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
